### ISSUE TITLE
A clerical error

### ISSUE THREAD

**Issue by cissusnar** [palacaze/gentoo-nanopi-r4s#1]
cp arch/arm64/boot/dts/rockchip/rk3399-nanopi-r4s.dtb "${R4S_GENTOO}/boot/rk3399-nanopi-r4s-${R4S_KERNEL_VER}.dtb"
need change to 
cp arch/arm64/boot/dts/rockchip/rk3399-nanopi-r4s.dtb "${R4S_GENTOO}"/boot/

**Comment by palacaze** [comment]
Hi Issac,

You are absolutely right, good catch!

On my device I have a symbolic link  rk3399-nanopi-r4s.dtb -> rk3399-nanopi-r4s-5.10.12.dtb
This makes it easier to switch between kernels.

**Comment by palacaze** [comment]
Fixed, thanks!
